### ISSUE TITLE
[成员管理] 以太坊中文翻译小组加入草稿

### ISSUE THREAD

**Issue by Riely007** [tog-ETH-er/tog-eth-er.github.io#5]
**以太坊中文翻译小组是谁？**
小组主要将优质的以太坊生态内容进行汉化，包括官网和 EF Research 的相关内容，让更多爱好者可以方便地了解以太坊生态以及其技术进展。
 
**做了什么？**
目前，小组已经帮助 ethereum.org 完成了上一版本的汉化工作。同时，这一版本和 EIP 的翻译也在进展中。
 
**加入 togETHer 之后想做的事**
可以更好服务于以太坊社区， 为社区发展提供翻译支持。
 
**了解更多：**
https://gitcoin.co/grants/3247/ethereum-translation-community-cn

**Comment by esther-ecn** [comment]
togETHer 决议情况：
20211115（togETHer 会议#21）
成员投票超过2/3，以太坊中文翻译小组加入提案通过，正式加入 togETHer，成为观察成员
