### ISSUE TITLE
[成员管理] Dapp Learning 学习小组加入草稿

### ISSUE THREAD

**Issue by bobjiang** [tog-ETH-er/tog-eth-er.github.io#6]
**Dapp Learning 学习小组是谁？**
什么是 Dapp Learning？
https://mp.weixin.qq.com/s/79eRMtB_yz8G6H8_saCeLw

**做了什么？**

- github仓库： https://github.com/rebase-network/Dapp-Learning
- bilibili视频：https://space.bilibili.com/382886213
- 油管视频：[youtube list](https://www.youtube.com/playlist?list=PLnP6dU8KobC8RT0CS0QGDDtVk9zdcEHhR)

**加入 togETHer 后想做的事情**
继续研究以太坊生态项目，以Defi和DAO为主，后续会慢慢扩大范围

**了解更多**
https://github.com/rebase-network/Dapp-Learning

**Comment by 0x68616f79756e** [comment]
支持

**Comment by freeyao** [comment]
DappLearning是很不错的项目，有相当多参与者，产出了大量内容。
个人一点小的疑问：作为Rebase社群孵化出的项目，DappLearning是怎样自主运营的，而不是作为Rebase的一个部门？

**Comment by yanyanho** [comment]
> DappLearning是很不错的项目，有相当多参与者，产出了大量内容。 个人一点小的疑问：作为Rebase社群孵化出的项目，DappLearning是怎样自主运营的，而不是作为Rebase的一个部门？

嗯，跟rebase理念相近但也有一些出入。帮助开发者更好了解blockchain和以太坊dapp开发，后面会尝试DAO治理方式管理此开源项目。
1 非盈利，不发币，会发些nft纪念 ，接受grant和捐赠；
2 专注研究和分享以太坊及layer2项目；
3 后面会有严格准入门槛，提PR和做分享才能进入。主要是为了一起维护开源项目和知识分享， 同时会给予贡献者成员奖励； 
4 越做越精，而非越做越大，发展海外开发者；
5 不是社区管理模式，希望吸引各个社区小伙伴开发者加入， 保持社区中立性，跟Rebase平等互助的关系。

**Comment by bobjiang** [comment]
as dapp learning joine, close this issue.
